### ISSUE TITLE
P2P code Review 14-9-2021

### ISSUE THREAD

**Issue by DyaryRaoof** [jonathastavares/Awesome-Books#2]

**Comment by Qoosim** [comment]
Good work @jonathastavares and @leolpaz . You guys did a wonderful job. My observation of the project is to empty the input textboxes after adding the book in order to avoid duplication of the same book in the book array. 
Also, try to stick to the usage of let and const as a way of declaring your variables so as to avoid the problem with the var way of declaration.
Good job once again for this wonderful job.

**Comment by DyaryRaoof** [comment]
Hi. Your project looks great so far and it is fully functional. however, I would like to add as optional advice instead of creating the `ButtonListener` function inside the `ListPopulate` function you can add event listeners right inside the `ListPopulate` function like this : 

```
function ListPopulate() {
  listObj.innerHTML = '';
  bookArray.forEach((bookElement, index) => {
    listObj.innerHTML += `<li class='text-center '>Book Name: ${bookElement.book} Book Author: ${bookElement.author} <br> <button type='button' value="${index}" class='remove-btn btn btn-secondary text-center mt-2'>Remove</button></li><br>`;
    const buttonArray = Array.from(document.getElementsByClassName('remove-btn'));
    buttonArray[index].addEventListener('click', RemoveBook);
  });
 
}
```

this way you don't have to iterate over the button to add event listeners later. so it saves you two or three lines of code.   and as I said this an optional advice.

**Comment by leolpaz** [comment]
Both issues are solved. Closing it.
