### ISSUE TITLE
Morning session P2P code review - 17/09/2021

### ISSUE THREAD

**Issue by lfmnovaes** [jonathastavares/Awesome-Books#6]
## Great work on your project @leolpaz 🙌 
I have some suggestions to make your code a bit better:
- Instead of creating multiple `.js` files for this project, you can try to unify everything into one and if you get some error from ESLint, you can follow their documentation on how to handle this issue. For example, the [enforce a maximum number of classes per file (max-classes-per-file)](https://eslint.org/docs/rules/max-classes-per-file)
- Instead of having the `luxon.js` file on your project (which can throw a lot of ESLint errors), you can just import it from their CDN. Placing this `<script src="https://cdn.jsdelivr.net/npm/luxon@2.0.2/build/global/luxon.min.js" integrity="sha256-CnZmNCHHUMy22/PJclCIISZ5Ib4MnUu+7ee5YNxtsZQ=" crossorigin="anonymous"></script>` on your HTML file and declaring it like this on your `.js` file: `const { DateTime } = require("luxon");`. If you face ESLint problems with this you can place `/* global luxon */
/* eslint no-undef: "error" */` on top of your `.js` file. Source: [Disallow Undeclared Variables (no-undef)](https://eslint.org/docs/rules/no-undef)

Keep in mind that these suggestions only solve the organization a little bit, your website is working perfectly. 😃

**Comment by dicodiaz** [comment]
## Hello @jonathastavares! Your project looks great, awesome job!

For this code review, I would recommend the following:

- Using HTML5 semantic tags will increase the semantic value of your document. I would recommend using the ```<main>``` tag instead of a ```<div>``` for the main container:
https://github.com/jonathastavares/Awesome-Books/blob/ae09fa65f59014abc9e1193979159c912f261676/index.html#L27
  - And ```<section>``` tags for each section with a relevant id:
https://github.com/jonathastavares/Awesome-Books/blob/ae09fa65f59014abc9e1193979159c912f261676/index.html#L29
https://github.com/jonathastavares/Awesome-Books/blob/ae09fa65f59014abc9e1193979159c912f261676/index.html#L41
https://github.com/jonathastavares/Awesome-Books/blob/ae09fa65f59014abc9e1193979159c912f261676/index.html#L56
- The ```class Load``` could be replaced by ```window.onload()``` and its static methods could be replaced by functions.
- Adding a screenshot of your website would make the README look more professional.

That's all, the rest is perfect. Keep up the good work! 😄

**Comment by Rocio01** [comment]
**Congratulations @leolpaz great project**

Your project accomplishes all the specifications and works nicely.
keep up the nice work.

kind regards
